language: generic 
sudo: required
services:
  - docker  

before_install:
  - docker build -t arfan-rfn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arfan-rfn/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-2"
  env: "Dockerreact2-env"  
  bucket_name: "elasticbeanstalk-us-west-2-667417033307"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
